name: Python package

on: [push, pull_request]

jobs:
  find_plugins:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.find_plugins_step.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - name: Find Plugin Directories
        id: find_plugins_step
        run: |
          dirs=$(find shared_airflow_components -mindepth 1 -maxdepth 1 -type d)
          json_array=$(echo "$dirs" | jq -R . | jq -s .)
          echo "dirs=${json_array}" >> $GITHUB_OUTPUT

  test_plugins:
    needs: find_plugins
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJson(needs.find_plugins.outputs.plugins) }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract Airflow Version
        id: extract_version
        run: |
          airflow_version=$(echo "${{ matrix.plugin }}" | sed -n 's/.*airflow-//p')
          echo "airflow_version=${airflow_version}" >> $GITHUB_OUTPUT

      - name: Run tests in Docker
        run: |
          docker run \
            -v "$(pwd)":"/usr/local/airflow/dags" \
            --rm \
            "apache/airflow:${{ steps.extract_version.outputs.airflow_version }}" \
            python -m unittest discover "/usr/local/airflow/dags/${{ matrix.plugin }}/tests"